### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by yuli06** [Aevis/Redmine-Joomla-authentication#1]
hi I want to try the tool that you provide because I need to share the same users in joomla and redmine, I put the rb file in the directory you indicated, and executed the query but I´m not sure what are the correct parameters to put, for example what refers the fiel name and base_dn
I hope you can explain me a bit more
thanks in advance

**Comment by Aevis** [comment]
Hi. This little project became obsolete when Redmine released their own script for a Joomla based authentication. Check this page, it's on the very bottom: http://www.redmine.org/projects/redmine/wiki/Alternativecustom_authentication_HowTo. There's also a good description of all the necessary parameters on that page. Hope it helps as I haven't used Joomla/Redmine in years and can't test it.
